<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Version"/>
  <PropertyGroup>
    <FileVersion>$(Version).0</FileVersion>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <NoWarn>NETSDK1233</NoWarn>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Rotherprivat</RootNamespace>
    <AssemblyTitle>CompositeMLKem - PQC-algorithms CompositeMLKem key exchange</AssemblyTitle>
    <Authors>Rotherprivat</Authors>
    <PackageId>Rotherprivat.CompositeMLKem</PackageId>
	  <PackageTags>PQC Post Quantum Cryptography Composite ML-KEM CompositeMLKem Key Exchange Key-Exchange</PackageTags>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>PQC-algorithms CompositeMLKem key exchange</Description>
  </PropertyGroup>
  
  <ItemGroup>
	  <None Include="../README.md" Pack="true" PackagePath="/" />
    <PackageReference Include="Microsoft.Bcl.Cryptography" Version="10.0.10" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="System.Formats.Asn1" Version="10.0.10" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.10" />
  </ItemGroup>

</Project>